### ISSUE TITLE
Python DLL is not loaded

### ISSUE THREAD

**Issue by AnhadSawhney** [Adrianotiger/ESPToolsGUI#1]
Hello, 

I tried to connect to my esp32 but pressing connect just gets an error in the terminal window:

`[E] Python DLL is not loaded.`

I have downloaded the latest zip folder from your releases and python3.dll is in the exes folder.

**Comment by Adrianotiger** [comment]
Hi,
thank you for the feedback.
Can you try to add manually this file (unzip python310.dll) to the "exes" folder?

[python310.zip](https://github.com/Adrianotiger/ESPToolsGUI/files/11146078/python310.zip)

It should be extracted from the exe automatically. But it doesn't work always, maybe because the exe is not signed...

**Comment by radunCZ** [comment]
With the provided dll it works fine. The problem is that the bundled pythond DLL is different to a one attached here (64kb vs 4MB in size). Maybe would be good to check/replace the bundled one.

BTW, nice piece of SW!

**Comment by Adrianotiger** [comment]
Uploaded version with the python 10 dll
